name: Test

on: [push ]

jobs:
  test:
    strategy:
      matrix:
        operating_system:
          - ubuntu:20.04
          #- windows-latest
          #- macos-latest
        nginx_version:
          - 1.21.6
          - mainline
          - 1
          - 1.21
          - latest
          - 1.21.6-perl
          - mainline-perl
          - 1-perl
          - 1.21-perl
          - perl
          - 1.21.6-alpine
          - mainline-alpine
          - 1-alpine
          - 1.21-alpine
          - alpine
          - 1.21.6-alpine-perl
          - mainline-alpine-perl
          - 1-alpine-perl
          - 1.21-alpine-perl
          - alpine-perl
          - 1.20.2
          - stable
          - 1.20
          - 1.20.2-perl
          - stable-perl
          - 1.20-perl
          - 1.20.2-alpine
          - stable-alpine
          - 1.20-alpine
          - 1.20.2-alpine-perl
          - stable-alpine-perl
          - 1.20-alpine-perl
    name: Check that the unut test are all passing
    runs-on: ${{matrix.operating_system}}
    steps:
      - name: Pull
        run: docker pull nginx:${{matrix.nginx_version}}
      - name: Run
        run: docker run -d  --publish 8080:80 --name webserver nginx
      - name: HTTP Request
        run: curl http://localhost:8080/
      - name: docker stop
        run: docker stop webserver
# 1. Lancer un conteneur NGINX
# 2. Vérifier que le serveur répond bien sur localhost
# 3. Stopper le conteneur
