name: Test

on: [ pull_request, push ]

jobs:
  test:
    name: Check that the unut test are all passing
    runs-on: ubuntu-20.04
    steps:
      - name: Docker image
        run: docker pull nginz:latest
      - name: Docker run
        run: docker run -d --name webserver -p 80:80 nginx

