name: Test

on: [ push ]

jobs:
  test:
    name: Check that the unut test are all passing
    runs-on: ubuntu-20.04
    steps:
      - name: Docker image
        run: docker pull nginx:latest
      - name: Docker run
        run: docker run -d --name webserver -p 80:80 nginx
      - name: HTTP REQUEST
        run: curl http://localhost
      - name: Docker stop
        run: docker stop webserver




