name: Test

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        operating_sys:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    
    name: Check that the unut test are all passing
    runs-on: ${{ matrix.operating_sys }}
    steps:
      - name: Docker image
        run: docker pull nginx:latest
      - name: Docker run
        run: docker run -d --name webserver -p 80:80 nginx
      - name: HTTP REQUEST
        run: curl http://localhost
      - name: Docker stop
        run: docker stop webserver




